CREATE TABLE books (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title VARCHAR(250),
    author VARCHAR(250),
    price DECIMAL(10, 2)
);

CREATE TABLE cart
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT,
    CONSTRAINT pk_cart PRIMARY KEY (id)
);

CREATE TABLE cart_item
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    book_id  BIGINT,
    quantity INT                                     NOT NULL,
    price    DOUBLE PRECISION                        NOT NULL,
    cart_id  BIGINT,
    CONSTRAINT pk_cart_item PRIMARY KEY (id)
);

ALTER TABLE cart
    ADD CONSTRAINT uc_cart_user UNIQUE (user_id);

ALTER TABLE cart_item
    ADD CONSTRAINT FK_CART_ITEM_ON_BOOK FOREIGN KEY (book_id) REFERENCES books (id);

ALTER TABLE cart_item
    ADD CONSTRAINT FK_CART_ITEM_ON_CART FOREIGN KEY (cart_id) REFERENCES cart (id);

ALTER TABLE cart
    ADD CONSTRAINT FK_CART_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);